# Generated by Django 2.2.6 on 2022-10-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.PositiveIntegerField(),
        ),
    ]
